FROM registry.access.redhat.com/ubi9/nodejs-22 AS frontend-builder

USER root
WORKDIR /app

COPY package*.json ./
RUN npm ci --no-audit --no-fund

COPY . ./

ENV NODE_OPTIONS=--max-old-space-size=512
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

FROM registry.access.redhat.com/ubi9/nodejs-22

USER root
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

COPY --from=frontend-builder /app/.next/standalone ./
COPY --from=frontend-builder /app/.next/static ./.next/static
COPY --from=frontend-builder /app/public ./public

RUN chgrp -R 0 /app && chmod -R g=u /app

USER 1001
EXPOSE 3000

CMD ["node", "server.js"]
