apiVersion: v1
kind: Service
metadata:
  name: {{ include "prisoners-dilemma.fullname" . }}-backend
  labels:
    {{- include "prisoners-dilemma.backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "prisoners-dilemma.backend.selectorLabels" . | nindent 4 }}
