apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prisoners-dilemma.fullname" . }}-frontend
  labels:
    {{- include "prisoners-dilemma.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "prisoners-dilemma.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prisoners-dilemma.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
            - name: BACKEND_URL
              value: {{ printf "http://%s-backend:%v" (include "prisoners-dilemma.fullname" .) .Values.backend.port | quote }}
            - name: HOSTNAME
              value: "0.0.0.0"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
