{{- if .Values.backend.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prisoners-dilemma.fullname" . }}-backend
  labels:
    {{- include "prisoners-dilemma.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  MODEL_TOKEN: {{ .Values.backend.secret.MODEL_TOKEN | quote }}
{{- end }}
